"""add order indexes

Revision ID: f5f7efdc32c1
Revises: 4576fc4791d8
Create Date: 2026-06-21 17:05:33.295984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5f7efdc32c1"
down_revision: Union[str, Sequence[str], None] = "4576fc4791d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill orphan rows to the smallest existing parent id (instead of a
    # hardcoded 1) so the new NOT NULL + FK constraints always have a valid target.
    default_order_id = "(SELECT MIN(id) FROM orders)"
    default_user_id = "(SELECT MIN(id) FROM users)"
    default_restaurant_id = "(SELECT MIN(id) FROM restaurants)"

    # items.order_id: add nullable, backfill existing rows, then enforce NOT NULL
    op.add_column("items", sa.Column("order_id", sa.Integer(), nullable=True))
    op.execute(f"UPDATE items SET order_id = {default_order_id} WHERE order_id IS NULL")
    op.alter_column("items", "order_id", existing_type=sa.Integer(), nullable=False)
    op.create_index(op.f("ix_items_order_id"), "items", ["order_id"], unique=False)
    op.create_foreign_key(None, "items", "orders", ["order_id"], ["id"])

    # orders already have NOT NULL user_id/restaurant_id; backfill defensively before indexing
    op.execute(
        f"UPDATE orders SET restaurant_id = {default_restaurant_id} WHERE restaurant_id IS NULL"
    )
    op.execute(f"UPDATE orders SET user_id = {default_user_id} WHERE user_id IS NULL")
    op.create_index(
        op.f("ix_orders_restaurant_id"), "orders", ["restaurant_id"], unique=False
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)

    # restaurants.owner_id: add nullable, backfill existing rows, then enforce NOT NULL
    op.add_column("restaurants", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.execute(
        f"UPDATE restaurants SET owner_id = {default_user_id} WHERE owner_id IS NULL"
    )
    op.alter_column(
        "restaurants", "owner_id", existing_type=sa.Integer(), nullable=False
    )
    op.create_index(
        op.f("ix_restaurants_owner_id"), "restaurants", ["owner_id"], unique=False
    )
    op.create_foreign_key(None, "restaurants", "users", ["owner_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "restaurants", type_="foreignkey")
    op.drop_index(op.f("ix_restaurants_owner_id"), table_name="restaurants")
    op.drop_column("restaurants", "owner_id")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_restaurant_id"), table_name="orders")
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_index(op.f("ix_items_order_id"), table_name="items")
    op.drop_column("items", "order_id")
    # ### end Alembic commands ###
